apiVersion: v1
kind: Service
metadata:
  name: pd-auth-server
  namespace: bbs-docker
  labels:
    app: pd-auth-server
spec:
  type: NodePort
  ports:
  - port: 8764
    name: pd-auth-server
    targetPort: 8764
    nodePort: 31004
  selector:
    app: pd-auth-server
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pd-auth-server
  namespace: bbs-docker
  labels:
    name: pd-auth-server
spec:
  serviceName: "pd-auth-server"
  replicas: 2
  selector:
    matchLabels:
      app: pd-auth-server
  template:
    metadata:
      labels:
        app: pd-auth-server
    spec:
      imagePullSecrets:
        - name: $SECRET_NAME
      containers:
        - name: pd-auth-server
          image: $IMAGE_NAME
          ports:
            - containerPort: 8764
  podManagementPolicy: "Parallel"