apiVersion: v1
kind: Service
metadata:
  name: bbs-auth-server
  namespace: bbs-docker
  labels:
    app: bbs-auth-server
spec:
  type: NodePort
  ports:
  - port: 8767
    name: bbs-auth-server
    targetPort: 8767
#    nodePort: 31006
  selector:
    app: bbs-auth-server
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: bbs-auth-server
  namespace: bbs-docker
  labels:
    name: bbs-auth-server
spec:
  serviceName: "bbs-auth-server"
  replicas: 2
  selector:
    matchLabels:
      app: bbs-auth-server
  template:
    metadata:
      labels:
        app: bbs-auth-server
    spec:
      imagePullSecrets:
        - name: $SECRET_NAME
      containers:
        - name: bbs-auth-server
          image: $IMAGE_NAME
          ports:
            - containerPort: 8767
  podManagementPolicy: "Parallel"