apiVersion: v1
kind: Service
metadata:
  name: pd-gateway
  namespace: bbs-docker
  labels:
    app: pd-gateway
spec:
  type: NodePort
  ports:
  - port: 8760
    name: pd-gateway
    targetPort: 8760
    nodePort: 31005
  selector:
    app: pd-gateway
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pd-gateway
  namespace: bbs-docker
  labels:
    name: pd-gateway
spec:
  serviceName: "pd-gateway"
  replicas: 2
  selector:
    matchLabels:
      app: pd-gateway
  template:
    metadata:
      labels:
        app: pd-gateway
    spec:
      imagePullSecrets:
        - name: $SECRET_NAME
      containers:
        - name: pd-gateway
          image: $IMAGE_NAME
          ports:
            - containerPort: 8760
  podManagementPolicy: "Parallel"